# Generated by Django 5.0.1 on 2024-03-06 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
    ]
