# Generated by Django 5.0.1 on 2024-03-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='count_comments',
            field=models.IntegerField(default=0),
        ),
    ]
