# Generated by Django 5.0.1 on 2024-03-10 18:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_post_count_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='count_comments',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='verified',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
